dotenv: .env
networks:
  default: development
  rinkeby:
    verify: True
    eth_usd_price_feed_addr: "0x9326BFA02ADD2366b30bacB125260Af641031331"
  mainnet-fork:
    verify: False
    eth_usd_price_feed_addr: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
  development:
    verify: False
  ganache-local:
    verify: False
dependencies:
  # <organization>/<repo-name>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.3.1
compiler:
  solc:
    remappings:
      # map imports to dependencies
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1"
